# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\amish_ac2c1jm\Desktop\UiFiles\re3project\loadingdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(257, 116)
        self.LoadingRdtProgressBar = QtWidgets.QProgressBar(Dialog)
        self.LoadingRdtProgressBar.setGeometry(QtCore.QRect(20, 60, 221, 31))
        self.LoadingRdtProgressBar.setProperty("value", 0)
        self.LoadingRdtProgressBar.setObjectName("LoadingRdtProgressBar")
        self.LoadingTextLabel = QtWidgets.QLabel(Dialog)
        self.LoadingTextLabel.setGeometry(QtCore.QRect(20, 10, 221, 51))
        self.LoadingTextLabel.setStyleSheet("font: 18pt \"Ink Free\";")
        self.LoadingTextLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LoadingTextLabel.setObjectName("LoadingTextLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LoadingTextLabel.setText(_translate("Dialog", "Loading RDT Files..."))
