# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\amish_ac2c1jm\Desktop\UiFiles\re3project\VerificationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.infodisplay = QtWidgets.QLabel(Dialog)
        self.infodisplay.setGeometry(QtCore.QRect(10, 10, 621, 461))
        self.infodisplay.setText("")
        self.infodisplay.setObjectName("infodisplay")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
